open HolKernel Parse boolLib bossLib helper_tactics;
open operationsTheory access_propertiesTheory read_propertiesTheory write_propertiesTheory;

val _ = new_theory "function_register_read_properties_lemmas";

Theorem FUNCTION_REGISTER_READ_IMPLIES_PENDING_ACCESSES_RESTRICTED_LEMMA:
!R W memory device_characteristics device1 device2 addresses byte.
  (device2, byte) = function_register_read device_characteristics device1 addresses
  ==>
  !channel_id.
    PENDING_ACCESSES_RESTRICTED R W memory (schannel device1 channel_id) (schannel device2 channel_id)
Proof
INTRO_TAC THEN
GEN_TAC THEN
REWRITE_TAC [PENDING_ACCESSES_RESTRICTED] THEN
REWRITE_TAC [PENDING_ACCESSES_RESTRICTED_FETCHING_BD] THEN
REWRITE_TAC [PENDING_ACCESSES_RESTRICTED_UPDATING_BD] THEN
REWRITE_TAC [PENDING_ACCESSES_RESTRICTED_TRANSFERRING_DATA] THEN
REWRITE_TAC [PENDING_ACCESSES_RESTRICTED_WRITING_BACK_BD] THEN
REWRITE_TAC [PENDING_ACCESSES_UNMODIFIED_FETCHING_BD] THEN
REWRITE_TAC [PENDING_ACCESSES_UNMODIFIED_UPDATING_BD] THEN
REWRITE_TAC [PENDING_ACCESSES_UNMODIFIED_TRANSFERRING_DATA] THEN
REWRITE_TAC [PENDING_ACCESSES_UNMODIFIED_WRITING_BACK_BD] THEN
ITAC device_register_read_lemmasTheory.FUNCTION_REGISTER_READ_PRESERVES_ALL_DMA_CHANNEL_PENDING_ACCESSES_LEMMA THEN
STAC
QED

Theorem FUNCTION_REGISTER_READ_PRESERVES_REGISTER_REQUESTING_READ_ADDRESSES_LEMMA:
!device_characteristics device1 device2 memory addresses byte.
  (device2, byte) = function_register_read device_characteristics device1 addresses /\
  REGISTER_REQUESTING_READ_ADDRESSES device_characteristics memory device1
  ==>
  REGISTER_REQUESTING_READ_ADDRESSES device_characteristics memory device2
Proof
INTRO_TAC THEN
ITAC device_register_read_lemmasTheory.FUNCTION_REGISTER_READ_PRESERVES_PENDING_REGISTER_RELATED_MEMORY_REQUESTS_LEMMA THEN
ITAC read_properties_lemmasTheory.EQ_PENDING_REGIESTER_RELATED_MEMORY_REQUESTS_PRESERVES_REGISTER_REQUESTING_READ_ADDRESSES_LEMMA THEN
STAC
QED

Theorem FUNCTION_REGISTER_READ_PRESERVES_DEVICE_REQUESTING_READ_ADDRESSES_LEMMA:
!device_characteristics device1 device2 memory addresses byte.
  (device2, byte) = function_register_read device_characteristics device1 addresses /\
  DEVICE_REQUESTING_READ_ADDRESSES device_characteristics memory device1
  ==>
  DEVICE_REQUESTING_READ_ADDRESSES device_characteristics memory device2
Proof
INTRO_TAC THEN
ETAC read_propertiesTheory.DEVICE_REQUESTING_READ_ADDRESSES THEN
CONJ_TAC THENL
[
 ETAC read_propertiesTheory.DMA_REQUESTING_READ_ADDRESSES THEN
 INTRO_TAC THEN
 AIRTAC THEN
 IRTAC FUNCTION_REGISTER_READ_IMPLIES_PENDING_ACCESSES_RESTRICTED_LEMMA THEN
 ITAC read_properties_lemmasTheory.PENDING_ACCESSES_RESTRICTED_PRESERVES_CHANNEL_R_LEMMA THEN
 STAC
 ,
 ITAC FUNCTION_REGISTER_READ_PRESERVES_REGISTER_REQUESTING_READ_ADDRESSES_LEMMA THEN
 STAC
]
QED

Theorem FUNCTION_REGISTER_READ_PRESERVES_REGISTER_REQUESTING_WRITE_ADDRESSES_LEMMA:
!device_characteristics device1 device2 memory addresses byte.
  (device2, byte) = function_register_read device_characteristics device1 addresses /\
  REGISTER_REQUESTING_WRITE_ADDRESSES device_characteristics memory device1
  ==>
  REGISTER_REQUESTING_WRITE_ADDRESSES device_characteristics memory device2
Proof
INTRO_TAC THEN
ITAC device_register_read_lemmasTheory.FUNCTION_REGISTER_READ_PRESERVES_PENDING_REGISTER_RELATED_MEMORY_REQUESTS_LEMMA THEN
ITAC write_properties_lemmasTheory.EQ_PENDING_REGIESTER_RELATED_MEMORY_REQUESTS_PRESERVES_REGISTER_REQUESTING_WRITE_ADDRESSES_LEMMA THEN
STAC
QED

Theorem FUNCTION_REGISTER_READ_PRESERVES_DEVICE_REQUESTING_WRITE_ADDRESSES_LEMMA:
!device_characteristics device1 device2 memory addresses byte.
  (device2, byte) = function_register_read device_characteristics device1 addresses /\
  DEVICE_REQUESTING_WRITE_ADDRESSES device_characteristics memory device1
  ==>
  DEVICE_REQUESTING_WRITE_ADDRESSES device_characteristics memory device2
Proof
INTRO_TAC THEN
ETAC DEVICE_REQUESTING_WRITE_ADDRESSES THEN
CONJ_TAC THENL
[
 ETAC DMA_REQUESTING_WRITE_ADDRESSES THEN
 INTRO_TAC THEN
 AIRTAC THEN
 IRTAC FUNCTION_REGISTER_READ_IMPLIES_PENDING_ACCESSES_RESTRICTED_LEMMA THEN
 ITAC write_properties_lemmasTheory.PENDING_ACCESSES_RESTRICTED_PRESERVES_CHANNEL_W_LEMMA THEN
 STAC
 ,
 ITAC FUNCTION_REGISTER_READ_PRESERVES_REGISTER_REQUESTING_WRITE_ADDRESSES_LEMMA THEN
 STAC
]
QED

Theorem FUNCTION_REGISTER_READ_PRESERVES_DEVICE_REQUESTING_READ_WRITE_ADDRESSES_LEMMA:
!device_characteristics device1 device2 memory addresses byte.
  (device2, byte) = function_register_read device_characteristics device1 addresses /\
  DEVICE_REQUESTING_READ_ADDRESSES device_characteristics memory device1 /\
  DEVICE_REQUESTING_WRITE_ADDRESSES device_characteristics memory device1
  ==>
  DEVICE_REQUESTING_READ_ADDRESSES device_characteristics memory device2 /\
  DEVICE_REQUESTING_WRITE_ADDRESSES device_characteristics memory device2
Proof
INTRO_TAC THEN
ITAC FUNCTION_REGISTER_READ_PRESERVES_DEVICE_REQUESTING_READ_ADDRESSES_LEMMA THEN
ITAC FUNCTION_REGISTER_READ_PRESERVES_DEVICE_REQUESTING_WRITE_ADDRESSES_LEMMA THEN
STAC
QED

val _ = export_theory();

